$(document).ready(function(e){
			$("#search-icon").click(function(e){
				$("#search-icon").hide();
				$("#search-div").fadeIn();
				$("#search-txt").focus();
			});
    		$('.sidenav').sidenav();
			$("#close-icon").click(function(e){
				$("#search-div").fadeOut();
				$("#search-icon").fadeIn();
			});
			$("#search-txt").blur(function(e){
				$("#search-div").hide();
				$("#search-icon").fadeIn();
			});
    		
    		$('.owl-carousel').owlCarousel({
			    loop:true,
			    margin:10,
			    responsiveClass:true,
			    responsive:{
			        0:{
			            items:1,
			            nav:true
			        },
			        600:{
			            items:3,
			            nav:false
			        },
			        1000:{
			            items:5,
			            nav:true,
			            loop:false
			        }
			    }
			})
			$('select').formSelect();
			 $('input#input_text, textarea#textarea2').characterCounter();
			 $('.modal').modal();
			 $('.datepicker').datepicker();

		});